apiVersion: v1
kind: ConfigMap
metadata:
  name: baoph1-config-map
data:
  DB_NAME: "baoph1-database"
  DB_USERNAME: "baoph1-user"
  DB_HOST: "postgresql-service"
  DB_PORT: "5432"
---
apiVersion: v1
kind: Secret
metadata:
  name: baoph1-secret
type: Opaque
data:
  kub: YmFvcGgxLXBhc3N3b3Jk